name: Build Python Wheel on PR to Staging

on:
  pull_request:
    branches:
      - staging
    types: [opened, synchronize, reopened]

jobs:
  build_wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Use your desired Python version, e.g., '3.9', '3.10', '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
          pip install databricks-sdk

      - name: Build Python wheel
        run: |
          # This command will look for pyproject.toml or setup.py in your repository root.
          # Ensure your setup.py/pyproject.toml correctly points to your 'packages' folder
          # or is configured to include it in the distribution.
          python -m build

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/*.whl # Uploads all .whl files found in the dist/ directory

      - name: Upload wheel to Databricks volume
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          python -c "
          from databricks.sdk import WorkspaceClient
          from databricks.sdk.service import catalog
          import glob

          w = WorkspaceClient()

          wheel_path = glob.glob('dist/*.whl')[0]
          wheel_name = wheel_path.split('/')[-1]
          volume_path = f'/Volumes/workspace/ds_cb_wheels/wheels'

          try:
            w.volumes.read(name = volume_path)
            print('Volume found')
          except:
            w.volumes.create(
              name = 'wheels',
              schema_name = 'ds_cb_wheels',
              catalog_name = 'workspace',
              volume_type = catalog.VolumeType.MANAGED
            )

          with open(wheel_path, 'rb') as f:
              w.files.upload(file_path=f'{volume_path}/{wheel_path}', contents=f.read(), overwrite=True)

          print(f'Uploaded {wheel_name} to {volume_path}')
          "